"""merge heads

Revision ID: 2a0599c2f04b
Revises: 9dc32543d522, ce66cad3b595
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0599c2f04b'
down_revision = ('9dc32543d522', 'ce66cad3b595')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
