"""empty message

Revision ID: 34249004f322
Revises: dfa73cf4e068
Create Date: 2025-09-08 21:00:05.653286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34249004f322'
down_revision = 'dfa73cf4e068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supervisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_responsable', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supervisor')
    # ### end Alembic commands ###
