"""empty message

Revision ID: 3a7d6f3dde80
Revises: 449bd9388b80
Create Date: 2025-09-12 01:48:03.194185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7d6f3dde80'
down_revision = '449bd9388b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.String(length=50), nullable=False),
    sa.Column('Nota_de_caso', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gestion')
    # ### end Alembic commands ###
