"""empty message

Revision ID: 449bd9388b80
Revises: a880a9662c42
Create Date: 2025-09-10 21:09:25.360756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449bd9388b80'
down_revision = 'a880a9662c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('fecha_creacion', sa.String(length=50), nullable=False),
    sa.Column('fecha_cierre', sa.String(length=50), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('fecha_evaluacion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    # ### end Alembic commands ###
