"""empty message

Revision ID: 4a61f9de2643
Revises: 59c4c9a7c820
Create Date: 2025-09-10 00:12:24.354388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a61f9de2643'
down_revision = '59c4c9a7c820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_supervisor', sa.Integer(), nullable=False),
    sa.Column('id_analista', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignacion')
    # ### end Alembic commands ###
