"""empty message

Revision ID: 73985ef1c9b5
Revises: 99a86d87b7a7
Create Date: 2025-09-21 23:45:25.414735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73985ef1c9b5'
down_revision = '99a86d87b7a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('texto',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('texto',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
