"""empty message

Revision ID: a92e8190bf39
Revises: 3d5e0a0b3f83
Create Date: 2025-09-15 15:41:39.870822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92e8190bf39'
down_revision = '3d5e0a0b3f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_ticket', sa.Integer(), nullable=False))
        batch_op.alter_column('id_gestion',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_analista',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_supervisor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'ticket', ['id_ticket'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_supervisor',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_analista',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_cliente',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_gestion',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id_ticket')

    # ### end Alembic commands ###
