"""empty message

Revision ID: dfa73cf4e068
Revises: 2456052339ba
Create Date: 2025-09-08 18:18:37.636730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa73cf4e068'
down_revision = '2456052339ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidad', sa.String(length=120), nullable=False))
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('especialidad')

    # ### end Alembic commands ###
